"""change journals table

Revision ID: ecb464c26bec
Revises: 
Create Date: 2024-07-06 18:27:35.198261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb464c26bec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('journals', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_column('journals', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('journals', 'due_date')
    op.drop_column('journals', 'date_created')
    # ### end Alembic commands ###
